### ISSUE TITLE
[Ошибки/Предложения] Математическая логика, 4 семестр

### ISSUE THREAD

**Issue by WoWaster** [WoWaster/lecture-notes#17]

**Comment by LiaSolo** [comment]
Косовская сказала, что у неё в эквивалентности тоненькая стрелочка (как в импликации), а то две одинаковые получаются


![3DA65B34-7539-4B41-8E70-AB97953BD39A](https://user-images.githubusercontent.com/92696842/221420017-88d94585-3211-4611-a01c-637e6702c45b.jpeg)

**Comment by LiaSolo** [comment]
Забыл Ашечку

![588B6CD2-8C2C-4FBF-BB14-605616AC6796](https://user-images.githubusercontent.com/92696842/221424786-bcc1d4db-8712-4396-8760-9fbe02e9758b.jpeg)

**Comment by WoWaster** [comment]
Конспект заброшен
