### ISSUE TITLE
[Ошибки/Предложения] Геометрия и топология, 3 семестр

### ISSUE THREAD

**Issue by WoWaster** [WoWaster/lecture-notes#8]

**Comment by tinarsky** [comment]
С. 14, f'(0) = (a, 0, 0)
![Screenshot from 2022-10-24 20-25-47](https://user-images.githubusercontent.com/87636986/197588444-f6d0b6ac-e703-4ff7-99f3-4539a97f996f.png)

**Comment by tinarsky** [comment]
*до прямой проходящей через точку f(t~0~)
![Screenshot from 2022-10-24 21-01-32](https://user-images.githubusercontent.com/87636986/197595091-6a49603e-573f-40fb-bf0b-a1e808282883.png)

**Comment by tinarsky** [comment]
С. 15.
*Тогда соприкасающаяся плоскость описывается уравнением z = 0 (это следует из вида f'(0) и f''(0)). ~Докажем это.~
![Screenshot from 2022-10-24 21-43-23](https://user-images.githubusercontent.com/87636986/197602445-0d8fc501-482e-45e8-92f7-cd9ea565cef6.png)

**Comment by tinarsky** [comment]
С. 16, штрих в третьем слагаемом пропущен.
![Screenshot from 2022-10-24 22-06-15](https://user-images.githubusercontent.com/87636986/197605840-3a723ae0-6c31-44bd-b479-76df5c8260ec.png)

**Comment by tinarsky** [comment]
k(s0) = (f''(s0))
![Screenshot from 2022-10-24 22-39-37](https://user-images.githubusercontent.com/87636986/197611457-d1d0e567-067c-4fda-a86d-106398248523.png)

**Comment by tinarsky** [comment]
С. 20, доказательство начинается со слов "Посмотрим, чем являются производные g...". До этого был другой способ, который не стали доводить до конца, потому что вторым оказалось проще.
![Screenshot from 2022-10-25 14-50-26](https://user-images.githubusercontent.com/87636986/197766095-db529560-2dde-4c2f-9a93-cfcda952bc0c.png)

**Comment by tinarsky** [comment]
*b1(s0)=b2(s0)
![Screenshot from 2022-10-25 21-33-31](https://user-images.githubusercontent.com/87636986/197854116-11947b55-54a4-4126-9a56-8c1632a22487.png)

**Comment by Aviu00** [comment]
C.29
![2022-11-06-151241_1366x768_scrot](https://user-images.githubusercontent.com/93730715/200170153-6824d1f7-2254-40a7-a0f8-8e7c54350f4f.png)

**Comment by Aviu00** [comment]
В конспекте дублированна глава о площади поверхности, а ведь там должен быть параграф о кривизне на поверхности.

**Comment by tinarsky** [comment]
![Screenshot from 2022-12-05 23-28-40](https://user-images.githubusercontent.com/87636986/205737195-221468f6-233c-4d6e-850d-4023b5624dfa.png)
С. 49,  у первого слагаемого индекс n.

**Comment by tinarsky** [comment]
![Screenshot from 2022-12-05 23-32-49](https://user-images.githubusercontent.com/87636986/205737511-9e02484f-91fb-4ac6-9957-ceecded0ba17.png)
С.49, по 2 штриха всем ψ не хватает

**Comment by zhitm** [comment]
![image](https://user-images.githubusercontent.com/64278750/208771043-0035a092-c981-46db-b3c3-88c4ad3eae8f.png)
надо бы написать, что альфа это угол AOD

**Comment by zhitm** [comment]
![image](https://user-images.githubusercontent.com/64278750/208887880-20ac4857-a268-4998-b600-b7927a18c4f9.png)

**Comment by zhitm** [comment]
59 страница 
![image](https://user-images.githubusercontent.com/64278750/209426487-03b2a0c2-c6c3-461a-9c27-244eb7aeeca4.png)
второй раз производная все же по v

**Comment by zhitm** [comment]
![image](https://user-images.githubusercontent.com/64278750/209567466-96e84904-50bb-4a26-9354-01e461f83e3f.png)
среди, а не средняя

**Comment by Mihey-38** [comment]
![image](https://user-images.githubusercontent.com/33938960/210803282-d988399b-4add-4feb-bce2-d74e869e3e40.png)

Начало 9 главы. Нужно "не зависит от _кривой_"

**Comment by Mihey-38** [comment]
![image](https://user-images.githubusercontent.com/33938960/210805495-b74f6694-c32d-4445-b9d0-949676e9ca17.png)

чуть ниже, в левой части равенства должна быть норма

**Comment by Mihey-38** [comment]
![image](https://user-images.githubusercontent.com/33938960/211195701-4218c2e5-6116-498a-9148-c970b0cf6b41.png)
 
u'^2

**Comment by Mihey-38** [comment]
![image](https://user-images.githubusercontent.com/33938960/211229603-e2993324-0994-454b-b9c2-964dbf9e3cad.png)
третья строчка _N_ = ...

**Comment by Mihey-38** [comment]
![image](https://user-images.githubusercontent.com/33938960/211230079-b4567dac-542d-45b6-a85b-0331e8a4c418.png)
во второй строке ожидается v вместо u

**Comment by Elizabeth013** [comment]
![image](https://user-images.githubusercontent.com/91689568/213923859-e75ab43d-9dc8-4775-88f5-a076406e5426.png)
Индексы: 3 1-1 3
В след строке аналогично и черточки)))

**Comment by KubEF** [comment]
стр. 51 (вводим соприкасающийся параболоид)
![image](https://user-images.githubusercontent.com/78155213/214020263-eff66603-f718-44fb-ac84-573611deac80.png)
Уравнение параболоида -- это в точности красное. $o(x^2 + y^2)$ -- это остаточек из формулы Тейлора, мы его отбрасываем, когда начинаем рассматривать уравнение параболоида

**Comment by KubEF** [comment]
![image](https://user-images.githubusercontent.com/78155213/214021399-af66e9b8-3002-40eb-be28-97af394215b6.png)
берём вторую производную, а не дифференцируем по квадрату

**Comment by Belgrak** [comment]
![image](https://user-images.githubusercontent.com/63420603/214222328-c66fb34e-6a99-4eec-b25f-989097e38827.png)

**Comment by BUYT-1** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/59949541/214360149-10a14b80-5e7c-461b-b3e1-56c00347ca54.png">
Это не соприкасающийся параболоид. Тут рассмотрены координаты, в котором соприкасающийся параболоид имеет канонический вид, но это не он сам.

**Comment by BUYT-1** [comment]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/59949541/214542074-3b0315bc-3a4c-428a-9323-43a8dca6f811.png">
это один и тот же символ

**Comment by BUYT-1** [comment]
![image](https://user-images.githubusercontent.com/59949541/214653247-13955508-524b-4c22-9535-9bf97ce05563.png)
По-честному бы это расписать

**Comment by BUYT-1** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/59949541/214884215-329a6efb-9e3e-4795-9512-a8a7012a39b8.png">
Тут `f'` (теорема 2.1)

**Comment by BUYT-1** [comment]
![image](https://user-images.githubusercontent.com/59949541/214929687-63138583-8baa-45e8-afc8-a914921f12f8.png)
Теорема Родрига (14.1, доказательство)

**Comment by BUYT-1** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/59949541/214930078-96b482e4-892e-4aab-89df-25e4be9a73ed.png">
Здесь берём саму поверхность в координатах, в которых соприкасающийся параболоид имеет канонический вид.

**Comment by BUYT-1** [comment]
![image](https://user-images.githubusercontent.com/59949541/214936383-523959b8-e5dd-4b89-a557-4378cf3bc82a.png)
(14.1)
